services:
  - type: web
    name: job-aggregator-backend
    env: python
    region: singapore
    plan: free

    rootDir: backend

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:8000
