company: "Google"
base_url: "https://careers.google.com"
job_url: "https://careers.google.com/jobs/results/"
source: "google_careers"

selectors:
  job_container: "div.gc-joblisting"
  title: "h2.gc-job-title"
  location: "span.gc-job-location"
  link: "a.gc-job-link"
  description: "div.gc-job-description"
